import {
  Code,
  Database,
  Globe,
  Smartphone,
  Server,
  Palette,
  Zap,
  Cloud,
  GitBranch,
  Monitor,
  Cpu,
  Shield,
  Layers,
  Box,
  FileCode,
  Braces,
  Terminal,
  Settings,
  Workflow,
  Package,
} from "lucide-react"

export const technologyIcons: Record<string, any> = {
    // Frontend
    HTML: Globe,
    CSS: Palette,
    JavaScript: FileCode,
    TypeScript: Braces,
    React: Code,
    ReactJs: Code,
    "Next.js": Monitor,
    "Vue.js": Code,
    Angular: Code,
    Svelte: Code,
    "Tailwind CSS": Palette,
    Bootstrap: Palette,
    Sass: Palette,
    SCSS: Palette,

    // Backend
    "Node.js": Server,
    "Express.js": Server,
    NestJS: Server,
    Django: Server,
    Flask: Server,
    FastAPI: Zap,
    "Spring Boot": Server,
    Laravel: Server,
    "Ruby on Rails": Server,
    "ASP.NET": Server,

    // Database
    MongoDB: Database,
    PostgreSQL: Database,
    MySQL: Database,
    SQLite: Database,
    Redis: Database,
    Firebase: Database,
    Supabase: Database,
    Prisma: Database,

    // Mobile
    "React Native": Smartphone,
    Flutter: Smartphone,
    Swift: Smartphone,
    Kotlin: Smartphone,
    Ionic: Smartphone,

    // Cloud & DevOps
    AWS: Cloud,
    Azure: Cloud,
    "Google Cloud": Cloud,
    Vercel: Cloud,
    Netlify: Cloud,
    Docker: Box,
    Kubernetes: Layers,
    Jenkins: Settings,

    // Tools & Others
    Git: GitBranch,
    GitHub: GitBranch,
    GitLab: GitBranch,
    Webpack: Package,
    Vite: Zap,
    Babel: Settings,
    ESLint: Shield,
    Prettier: Settings,
    Jest: Shield,
    Cypress: Shield,
    Figma: Palette,
    "Adobe XD": Palette,
    Photoshop: Palette,
    GraphQL: Workflow,
    "REST API": Server,
    "Socket.io": Zap,
    WebSocket: Zap,
    Stripe: Shield,
    PayPal: Shield,
    Auth0: Shield,
    JWT: Shield,
    OAuth: Shield,
    Electron: Monitor,
    PWA: Smartphone,
    WebRTC: Zap,
    "Three.js": Cpu,
    "D3.js": Cpu,
    "Chart.js": Cpu,
    "Material-UI": Palette,
    "Ant Design": Palette,
    "Chakra UI": Palette,
    "Styled Components": Palette,
    Emotion: Palette,
    Storybook: Package,
    Lerna: Package,
    Yarn: Package,
    npm: Package,
    pnpm: Package,
    Turborepo: Package,
    Nx: Package,
    Rollup: Package,
    Parcel: Package,
    ESBuild: Zap,
    SWC: Zap,
    Rust: Terminal,
    Go: Terminal,
    Python: Terminal,
    Java: Terminal,
    "C#": Terminal,
    "C++": Terminal,
    PHP: Terminal,
    Ruby: Terminal,
    Scala: Terminal,
    Dart: Terminal,
    R: Terminal,
    MATLAB: Terminal,
    Shell: Terminal,
    Bash: Terminal,
    PowerShell: Terminal,
}

export const getTechnologyIcon = (technology: string) => {
  const normalizedTech = technology.trim()
  return technologyIcons[normalizedTech] || Code // Default icon
}

export const getTechnologyColor = (technology: string): string => {
  const colorMap: Record<string, string> = {
    // Frontend - Blue tones
    HTML: "text-orange-500",
    CSS: "text-blue-500",
    JavaScript: "text-yellow-500",
    TypeScript: "text-blue-600",
    React: "text-cyan-500",
    ReactJs: "text-cyan-500",
    "Next.js": "text-gray-800",
    "Vue.js": "text-green-500",
    Angular: "text-red-500",
    Svelte: "text-orange-600",
    "Tailwind CSS": "text-teal-500",
    Bootstrap: "text-purple-500",
    Sass: "text-pink-500",
    SCSS: "text-pink-500",

    // Backend - Green tones
    "Node.js": "text-green-600",
    "Express.js": "text-gray-600",
    NestJS: "text-red-600",
    Django: "text-green-700",
    Flask: "text-gray-700",
    FastAPI: "text-teal-600",
    "Spring Boot": "text-green-600",
    Laravel: "text-red-500",
    "Ruby on Rails": "text-red-600",
    "ASP.NET": "text-blue-600",

    // Database - Purple tones
    MongoDB: "text-green-500",
    PostgreSQL: "text-blue-700",
    MySQL: "text-orange-500",
    SQLite: "text-blue-500",
    Redis: "text-red-500",
    Firebase: "text-yellow-500",
    Supabase: "text-green-500",
    Prisma: "text-indigo-600",

    // Mobile - Pink tones
    "React Native": "text-cyan-500",
    Flutter: "text-blue-500",
    Swift: "text-orange-500",
    Kotlin: "text-purple-500",
    Ionic: "text-blue-500",

    // Cloud - Sky tones
    AWS: "text-orange-500",
    Azure: "text-blue-500",
    "Google Cloud": "text-blue-500",
    Vercel: "text-gray-800",
    Netlify: "text-teal-500",
    Docker: "text-blue-500",
    Kubernetes: "text-blue-600",

    // Default
    default: "text-gray-500",
  }

  return colorMap[technology.trim()] || colorMap.default
}
